name: Build

on:
    push:
        branches:
            - master

jobs:
    build:
        name: 'Build'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'

            - run: npm ci
            - run: npm run build
